project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "_team.qmd"
    - "*/index.qmd"         # <- new sport pages
    - "*/*/index.qmd"       # module pages
    - "by-statsds-topic.qmd"
  exclude:
    - "mma/**"              # skip anything under mma b/c of ggmosaic issue
metadata-files:
  - sidebar-sports.yml
    
website:
  google-analytics: "G-JVDQHPRYT1"
  cookie-consent:
    type: implied
    prefs-text: "Manage cookies"
  title: "Baylor APU SCORE Module Preprint Repository"
  page-footer: 
    center:
      Maintained by Katie Fitzgerald <br>
    
      We use cookies to track usage statistics 
      to help measure impact of the materials
      for authors. Please consider allowing 
      tracking cookies.
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://modules.scorenetwork.org/
        text: SCORE Module Repository
      - href: https://data.scorenetwork.org/
        text: Data Repository
  sidebar:
    contents: auto
    collapse-level: 1

format:
  html:
    theme:
      - flatly
      - score.scss
    toc: true

execute:
  freeze: auto
